
CREATE TABLE IF NOT EXISTS users
( id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  passHash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS apps
( id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  secret TEXT NOT NULL UNIQUE
);
